Second project (form project)
ositaadimma/form-project pull request #1
Opened 2020-07-14 21:37 UTC by ositaadimma

2020-07-14 21:45 UTC, expjazz requested changes
## Hey Team

#### Unfortunately I need to mark this submission as invalid because the Pull Request does not have a short summary.

You can check more about it [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)

### This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready! :pray:

Good Luck and Happy Coding :+1: :

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

2020-07-14 22:58 UTC, BrittanyBlake requested changes
### Status: Changes Required ♻️ 
****
### Hi @ositaadimma  and @jssarrazolaa ! 👋 
You have done a wonderful job with your project so far! It looks really good! 👏 👏 👏  There are just a few issues that need to be resolved before you can move on: ⬇️ 
****

- [ ] There are some areas where you are using inefficient CSS selectors and repeating yourself. 

- [ ] You are using a lot of ID selectors. You can class selectors for elements that use the same rules rather than having many ID selectors that can only apply to one element. 

- [ ] Take a look at the different `<input>` types and how to use them. I have added a useful article in the comments 😄 

- [ ] It appears as though your linter checks are not configured properly.  Please take a look at the [Microverse linters repository](https://github.com/microverseinc/linters-config/tree/master/html-css) and make sure that you have added everything correctly.


****
### Please make the required changes and resubmit for a new code review once you are ready 🙏

Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

2020-07-14 22:58 UTC, BrittanyBlake commented on style/style.css
> +}
- [ ] You haven't added styles here so there is no reason to keep this in your file. It can be removed.

2020-07-14 22:58 UTC, BrittanyBlake commented on style/style.css
> +}
- [ ] These both appear to do the same thing. It is bad practice to repeat the same rules. You can consolidate these by adding 1 common class to the elements you want to be styled in this way.

- You can read more about good and bad CSS practices in [this article](https://speckyboy.com/good-bad-css-practices/).

![Screen Shot 2020-07-15 at 12 39 19 AM](https://user-images.githubusercontent.com/48804258/87483274-a0b3ef80-c633-11ea-8238-5a6b11ac0b9f.png)

2020-07-14 22:58 UTC, BrittanyBlake commented on index.html
> +                            <input name="number" type="text">
- [ ] This input section should have a type of "tel". You can take a look at [this article](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) for more information on Form input types. 

![Screen Shot 2020-07-15 at 12 52 16 AM](https://user-images.githubusercontent.com/48804258/87484014-6fd4ba00-c635-11ea-92df-e019eb056fa6.png)

2020-07-15 16:27 UTC, expjazz requested changes
## Status: Changes Requested :red_circle: 

#### Hello team! You did a great job on this project. The page looks really good and you worked on all the changes my colleague asked you. The only problem is:

- [ ] You have linter errors

#### Kindly fix that and submit for a new review.

Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

2020-07-15 17:36 UTC, expjazz approved these changes
## Status: Project Approved :clap: 

#### Congratulations again team! Good luck on the next projects :pray: 

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

2020-07-15 17:54 UTC, merged